### ISSUE TITLE
Support fix without fetch/pull

### ISSUE THREAD

**Issue by stevelacey** [tj-django/django-migration-fixer#125]
### Is your feature request related to a problem? Please describe.

The pull/fetch behavior is quite surprising, and doesn't work in some environments such as Docker, where the container does not have permission to fetch/pull from the remote.

For me it launched an ssh warning, because it's a Docker, with no access to my GitHub account, which lead me to reading the source to confirm the library was doing nothing untoward before proceeding, and then it didn't work anyway.

### Describe the solution you'd like?

It'd be great if there was an option to skip that step, and assume the user has already brought their base branch up to date, commenting out https://github.com/tj-django/django-migration-fixer/blob/main/migration_fixer/management/commands/makemigrations.py#L115-L126 seems to do the trick.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jackton1** [comment]
@stevelacey This should be resolved in the latest release
